name: Publish NuGet Package

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'NKnife.TDMS.sln'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'

    - name: Restore dependencies
      run: dotnet restore /p:EnableWindowsTargeting=true

    - name: Build
      run: dotnet build --configuration Release --no-restore /p:EnableWindowsTargeting=true

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg /p:EnableWindowsTargeting=true

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
